[rospy.client][INFO] 2020-09-14 07:58:36,493: init_node, name[/car_driver_node], pid[18031]
[xmlrpc][INFO] 2020-09-14 07:58:36,494: XML-RPC server binding to 0.0.0.0:0
[xmlrpc][INFO] 2020-09-14 07:58:36,494: Started XML-RPC server [http://192.168.43.172:37443/]
[rospy.init][INFO] 2020-09-14 07:58:36,495: ROS Slave URI: [http://192.168.43.172:37443/]
[rospy.impl.masterslave][INFO] 2020-09-14 07:58:36,495: _ready: http://192.168.43.172:37443/
[rospy.registration][INFO] 2020-09-14 07:58:36,497: Registering with master node http://192.168.43.172:11311
[xmlrpc][INFO] 2020-09-14 07:58:36,498: xml rpc node: starting XML-RPC server
[rospy.init][INFO] 2020-09-14 07:58:36,596: registered with master
[rospy.rosout][INFO] 2020-09-14 07:58:36,597: initializing /rosout core topic
[rospy.rosout][INFO] 2020-09-14 07:58:36,606: connected to core topic /rosout
[rospy.simtime][INFO] 2020-09-14 07:58:36,610: /use_sim_time is not set, will not subscribe to simulated time [/clock] topic
[rospy.internal][INFO] 2020-09-14 07:58:36,861: topic[/rosout] adding connection to [/rosout], count 0
[rospy.internal][INFO] 2020-09-14 07:58:36,865: topic[/zxcar/get_vel] adding connection to [/heima_base_node], count 0
[rospy.internal][INFO] 2020-09-14 07:58:36,871: topic[/zxcar/imu] adding connection to [/apply_calib], count 0
[rospy.internal][INFO] 2020-09-14 07:58:36,873: topic[/zxcar/magnetic] adding connection to [/apply_calib], count 0
[rospy.internal][INFO] 2020-09-14 07:59:08,462: topic[/cmd_vel] adding connection to [http://192.168.43.172:45439/], count 0
[rospy.internal][ERROR] 2020-09-14 08:00:07,262: Unable to initiate TCP/IP socket to 192.168.43.172:43355 (http://192.168.43.172:45439/): Traceback (most recent call last):
  File "/opt/ros/melodic/lib/python2.7/dist-packages/rospy/impl/tcpros_base.py", line 562, in connect
    self.read_header()
  File "/opt/ros/melodic/lib/python2.7/dist-packages/rospy/impl/tcpros_base.py", line 657, in read_header
    self._validate_header(read_ros_handshake_header(sock, self.read_buff, self.protocol.buff_size))
  File "/opt/ros/melodic/lib/python2.7/dist-packages/rospy/impl/tcpros_base.py", line 600, in _validate_header
    raise TransportInitError("remote error reported: %s"%header['error'])
TransportInitError: remote error reported: node shutting down

[rospy.internal][WARNING] 2020-09-14 08:00:08,266: Unknown error initiating TCP/IP socket to 192.168.43.172:43355 (http://192.168.43.172:45439/): Traceback (most recent call last):
  File "/opt/ros/melodic/lib/python2.7/dist-packages/rospy/impl/tcpros_base.py", line 562, in connect
    self.read_header()
  File "/opt/ros/melodic/lib/python2.7/dist-packages/rospy/impl/tcpros_base.py", line 657, in read_header
    self._validate_header(read_ros_handshake_header(sock, self.read_buff, self.protocol.buff_size))
  File "/opt/ros/melodic/lib/python2.7/dist-packages/rosgraph/network.py", line 357, in read_ros_handshake_header
    d = sock.recv(buff_size)
error: [Errno 104] Connection reset by peer

[rospy.internal][INFO] 2020-09-14 08:00:08,267: topic[/cmd_vel] removing connection to http://192.168.43.172:45439/
[rospy.internal][INFO] 2020-09-14 08:00:14,503: topic[/cmd_vel] adding connection to [http://192.168.43.172:43649/], count 0
[rospy.internal][ERROR] 2020-09-14 08:01:17,522: Unable to initiate TCP/IP socket to 192.168.43.172:42975 (http://192.168.43.172:43649/): Traceback (most recent call last):
  File "/opt/ros/melodic/lib/python2.7/dist-packages/rospy/impl/tcpros_base.py", line 562, in connect
    self.read_header()
  File "/opt/ros/melodic/lib/python2.7/dist-packages/rospy/impl/tcpros_base.py", line 657, in read_header
    self._validate_header(read_ros_handshake_header(sock, self.read_buff, self.protocol.buff_size))
  File "/opt/ros/melodic/lib/python2.7/dist-packages/rospy/impl/tcpros_base.py", line 600, in _validate_header
    raise TransportInitError("remote error reported: %s"%header['error'])
TransportInitError: remote error reported: node shutting down

[rospy.internal][WARNING] 2020-09-14 08:01:18,526: Unknown error initiating TCP/IP socket to 192.168.43.172:42975 (http://192.168.43.172:43649/): Traceback (most recent call last):
  File "/opt/ros/melodic/lib/python2.7/dist-packages/rospy/impl/tcpros_base.py", line 560, in connect
    self.socket.connect((dest_addr, dest_port))
  File "/usr/lib/python2.7/socket.py", line 228, in meth
    return getattr(self._sock,name)(*args)
error: [Errno 111] Connection refused

[rospy.internal][INFO] 2020-09-14 08:01:18,528: topic[/cmd_vel] removing connection to http://192.168.43.172:43649/
[rospy.internal][INFO] 2020-09-14 08:01:40,905: topic[/cmd_vel] adding connection to [http://192.168.43.172:37445/], count 0
[rospy.internal][ERROR] 2020-09-14 08:02:43,910: Unable to initiate TCP/IP socket to 192.168.43.172:38601 (http://192.168.43.172:37445/): Traceback (most recent call last):
  File "/opt/ros/melodic/lib/python2.7/dist-packages/rospy/impl/tcpros_base.py", line 562, in connect
    self.read_header()
  File "/opt/ros/melodic/lib/python2.7/dist-packages/rospy/impl/tcpros_base.py", line 657, in read_header
    self._validate_header(read_ros_handshake_header(sock, self.read_buff, self.protocol.buff_size))
  File "/opt/ros/melodic/lib/python2.7/dist-packages/rospy/impl/tcpros_base.py", line 600, in _validate_header
    raise TransportInitError("remote error reported: %s"%header['error'])
TransportInitError: remote error reported: node shutting down

[rospy.internal][WARNING] 2020-09-14 08:02:44,912: Unknown error initiating TCP/IP socket to 192.168.43.172:38601 (http://192.168.43.172:37445/): Traceback (most recent call last):
  File "/opt/ros/melodic/lib/python2.7/dist-packages/rospy/impl/tcpros_base.py", line 560, in connect
    self.socket.connect((dest_addr, dest_port))
  File "/usr/lib/python2.7/socket.py", line 228, in meth
    return getattr(self._sock,name)(*args)
error: [Errno 111] Connection refused

[rospy.internal][INFO] 2020-09-14 08:02:44,913: topic[/cmd_vel] removing connection to http://192.168.43.172:37445/
[rospy.core][INFO] 2020-09-14 08:02:49,904: signal_shutdown [signal-2]
[rospy.internal][INFO] 2020-09-14 08:02:49,916: topic[/zxcar/get_vel] removing connection to /heima_base_node
[rospy.internal][INFO] 2020-09-14 08:02:49,917: topic[/rosout] removing connection to /rosout
[rospy.internal][INFO] 2020-09-14 08:02:49,918: topic[/zxcar/imu] removing connection to /apply_calib
[rospy.internal][INFO] 2020-09-14 08:02:49,919: topic[/zxcar/magnetic] removing connection to /apply_calib
[rospy.impl.masterslave][INFO] 2020-09-14 08:02:49,919: signal-2
